AllCops:
  Include:
    - '**/Rakefile'
    - 'plugins/**/*'
  Exclude:
    - 'test/**/*'
    - 'cookbooks/**/*'
    - '.bundle/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'

PerlBackrefs:
  Enabled: false

MethodLength:
  Enabled: false
