language: ruby
bundler_args: --without kitchen_vagrant
rvm:
- 2.0.0
before_install:
- echo -n $RS_KEY_CHUNK_{0..30} >> ~/.ssh/id_rs.base64
- cat ~/.ssh/id_rs.base64 | tr -d ' ' | base64 --decode > ~/.ssh/id_rsa
- echo -n $RS_PUB_KEY_CHUNK_{0..30} >> ~/.ssh/id_rs.pub.base64
- cat ~/.ssh/id_rs.pub.base64 |tr -d ' ' | base64 --decode > ~/.ssh/id_rsa.pub
script:
- bundle exec rake style
- bundle exec kitchen test $KITCHEN_INSTANCE
after_script:
- bundle exec kitchen destroy $KITCHEN_INSTANCE
env:
  global:
  - KITCHEN_YAML=.kitchen.rackspace.yml
  - SSH_KEY_FILE=~/.ssh/id_rs.pem
  - RS_FLAVOR=performance1-4
  - RS_REGION=dfw
  - secure: YUMfp8gkovHOagrhb1v3vXuzxXo2Rd/4pe5INd1bQTVhFja7+BIPZe8+/hT6MrKmjDVap8+lz6402tumtwQaFy9GTJJ2499bJIggeRnN7w961LHIRsvYndnqG71zMAxREY6Rqj8PA1ykDANggDvC/nTcuKJrGbV4MnaWBS19aFU=
  - secure: BPoWapfSaM0UBgJ8ZL6PgRCt42O9gEn0maNmmZ7vzkBi0NIvmvE3lhLqeK/aKNvX6FpWbGMsesrUX6aKhJtHsUW1KlKpa7JTmXcx7fbCEhhdMFl1te4xaX/a8GWZHGraNKLqw4ylEtSVKereq1uA0B5J/LUf4w7QAC5iWRLDrvU=
  - secure: LreRKqtUS4/7PD6ukhl4zk0bS9z2NyGDWV4As3+3j2uawY6Eh3Xy0wNrG3J6zmuf0vsyCOVjhaI5pjnHg8/Nj9nbb2JDBJiqrdIjsc4yBtpa1XL7jslIuc9gwK7qrCmQeCKkjZTo3w679UzbaLB9ADJRKff30m46Nh5x2FfVHl0=
  - secure: GE+34g49bjK2dkdw8k5/VkmSK/jWdDHUZnDE7Zr5WGjDlXqvu3nnDMqvntcmFKtb6jZzlggNglG3dBJ+pWXOpoOl0XjwTx5N085r0juuEv+V0UKMPmO25qgs8hqhuxccKXvyh498WdTtp+ITHO16unbjeSRpRWj0xg6b1eTv5xg=
  - secure: feUKWNmpi8nLdIBU27/LqwiU9cYkdrcXwpaZccEyqlenaSULAXAc8PpGxWCSYvLtceCeY165TROwFQx7NRRd2V92whdNB4KvRpfrYkB3BqG2SJ/sbyQAurXZYRujnynYviBHpBWkKRF1MQFV24IYypOTfHVCBrV7iCZLjpfYvQw=
  - secure: XG6Sg0OjrfXZTyZ0vygURqdZnug3u0qICzlGbtv1gHD4gHvgeT3z2YW8cERuZh3VaTt0aPx63N3XCU+q5nFJAaowv5jxU5NyZikgRIZ1cfpu8ofn35OXSOqIwlGUMPxYAuzD103nLLurOL3QDOnZ9bRD/D3/Q2GEaeQDcTIccew=
  - secure: Pf3g6/0263Y7ThNSFhSpSDzJN5UL+xLta09xp7Bpm7sKqT2B8roGMsbOK2UlCjAPc2TRo2Rc1UKsFL1MiJ+xx7TWTmk2PuAxPrzas7vsm5uJfAC1qPVmoaIIkwnbYsL6EykugVvKwQiPSEY+3WWPmwEUltx3NUpJe3wRt6CowdQ=
  - secure: Z8vuHHMGZiMkDSOMY/NMaCdrzBDfuC9MuOKYM+tcjcLp1Y8st9JZqsIiPY2vgHUDAwAjSJrQ2/dWbDjIc6K/UyqyyKfl7+3JVkvbAJaXC/1ZF21goGeJjjGxli1xIQ0BjuBxfSKNMCH7QRG/uKVrEiTs0Cxe11fyljWbdVxJ7wc=
  - secure: D0+Wo/8G3NWmC5pwykLyrwAAm6xUSXuh2iVD59MiMwpyvHLTuzLUOBLArXppkcaodOmDKTNjfOOVLe3LfxLltwF12RkRAFmhKz3PseGraFOI1yNp2xXdXJZzvD13ISvbHunQK1FJfIKUzk9L7pRXpkJJsfz2EFYCSGjspfWv4AY=
  - secure: Rl8PosSPEMLZ34PI6enu4iFQarA/fJQba0VwmJ9wtNu2INWP0BEpy61jbYhvR8IJoXSM9PEHGAZyjEy2myaF5n43pvTiH7qQNy3gisgjs1MCbnFUiBQ5xMhGnG+ACHe8Jj0RoH+TVTuqolycBfcHujKcJIp6M5wo4Zf0dUccUEk=
  - secure: OnWsTymB8EtZEAsfggYhf/MraLG7Aqwkuufeib6Tv7wsP32U8z9GZySWThRu+n0ZP4cCCW1AaCtPhr87Ile3Etr9S2tU9JJ4Ws/6yKuaorPGH0ajfVuHbK2QQeX5JP13doLibO33oNrXd8Icu7VshXP/qQGuJy05oxb4kU2pnRw=
  - secure: LwMl4HnEzSMfCyyPSrgJmXp5s/HZJGH0cGgTNKxQ+Dx3aUr/etSQ39Gtt9+55pktNgOk4G+v90REerMxXuqe5A/3C9rfqI4LMXvmgRRLKHarU0/97J/soaOF4SM8514Sw18Au7zan3NQETBrsXGJ6NEcXaNrALUHk5fDWmTk0LI=
  - secure: cnEPWNgvb5SaUEwRESCY0/qxd/RaS9AYTxY+81Yqg8EHDOTqa9gnLLe29LTaD6P87QLKrFNA5XO4JQBT00jDb0niq/cWeMPVQ73UpH0zjf5vzXfrEkSYGdQ+0CUPKV8c8vjs3Gf91qzo2fb/+mMwKLmKl6KvAs5aMykpS7sA1/M=
  - secure: eMAxQoQTUAyUq8NG2S65PeZXd9f4QLEvWRyFI63FXLoxBwHpRkaBvuryCOCovwouUIpp1tIR8BRkvS2a+NkbMdR15RSw9/r9Um0lMczfHYeVBHsLGpMUbdUPpKK08DrLoa+/Vm7ADEX2eUQBcka3j5puVDL4EqXnZQPhHMAe/+M=
  - secure: MSiy4eXDNrGaPEV9pO7QDBKh9wPebnywVXeT3WF1CXIUs90dd0D/JZuQ+gy9DszifZk2TRPNYC7u49Kjb+xWiNcAVdWBVb/Zh+gMr6EqrIXS3cAQtuBv65vp4H8eeD1uk1cn2hJWLhftpIqWM3S21Xt9WdfT55f8CU3giY7+hMk=
  - secure: IfU3wYe/1V9jN5St8XVkz+EkIO4z0comf3g0pRxyEGonBymjei4HzpNzpdh/wIfCOmmrN3F+Z18raA9jzTc0/6DF6aatfS3ZWzQ7e7nImxMa4zjHEyJPshhgrEZPB0SkYsinR1XVa6kqZBMm8qqnDhf6RKeNNh7HPpAX2CvnJtA=
  - secure: EgE5Pcv5yfJjcIygp8mEasZ+fuKGiqLg07KLd5cxLJLf8xpkC49ZOhxKZgneHLRwkae4234FFmMW7s1UH0d5yuG6Rxg9v1lVdrlDxlLxxNEhc+R4RKpLUvxXaHariFx7xPswXFay3wleOhRMeIc6qq7yin7eS06DVhoiVpdgdM0=
  - secure: af1QTK4kXBq9ovxTtk/VPa4Tk4IxpWaIBYvvunWl8uRhTf1TQm6paXFfg3isf2VHtmKJclkmwd+3kzvSkgvgBnWb5A1Vmuy7CAQ4bsviKQfwBDnMXgfCC8dK3tOp8DsxzTEo2TNAW3DXdwDfotdOWyAx7D6k/bp/1PKZ94dljWA=
  - secure: bEUweQZ0WNNiW0BJ6TDHGlsa0fCts3+jArpE2K8F2jE7li474oOenI8jwBXNYgeHHOas+oVPi916jyh1Ojbe40yspq5sdSFFkUmzlYBpD3lYInk/gowX/kuR7Lbl6c42TNVPHEZ4ahCaQr6fEia8gG20hpA5BRGSYExkuO8qGYw=
  - secure: cz0cRtFCPi/TJqDL9N3EzhtAM9abhotT69S0z6z0lJyncyY5nQr9Q8Obb1p3Ool/wG+c5/jrIftgYSItJ/k/Lh7RbVvj+02RdWdcIN5RZNZyho2mhUrAKFw6ZWlafKYPlrm5UgnfbwvOMi4D8nslWSDkYe2yXDzqmRDUUvej/Uk=
  - secure: XyvzQ3x7yAAzZWMsismaat+ZRXFfsrCXjccoaojvmCZYPPpshyXQkHvVP2k4l+fZpd85sWK7GeSfKpPCS8/XlLSBD5vhJjNBf4XTTLq/TgLU+3Z7r8ZGIvnGs4nybOpHj2zktj4ki6alL3JvDemkkk0A+/cinvKEQs+dEMp2jmM=
  - secure: fXxzlvOz22Fg4SF7ELU3M2qcJYP2SiKx71PvphUmYZ8WmKQyDehr99A14dUUAPol/skpJ8AkS+e77hNJFq2tgTGVyTOPFBvywAv0LFSok2CBCJdCG6v9dFgeziH07DiJagsgjVySh3x3vdTLIF9tGVvMuGN7CIXwN7rLnBfNJdk=
  - secure: FnQimdgLZe4P7/kwmNV7/6MMAtYJJ5GEjUXSvAWrhUrU4AZQJY6gwitzCyPEtnc5TFPYmSbQRl3O2muB+ULVGxHrvCBxYeiSyfKGhZ5ilegk9FwL0XAxLWe76e7n+sG2Z+So+li4p6KW0K+oeWNHy6y1xWR2NRfGA0lH2+wVJD4=
  - secure: H124S9GfD2zx3KNuE5TUhQd8M020G/zfSyOB770GicAU8IdFXDJy3oUOA8CRWnkpghBZEfuPtQIkgujKs8lu9IBuOBecs9S7HFcHds1KNz5k0pMJj0kj23tHwWPZiOJdzhsUCN/MW413GQCtvCN64WJgN3JRZw+2a1DKcxqYn2I=
  - secure: Cs2skOAMCSABwFln+7N/uORvACYd9iLdUeLcIm/7mQZV7LNaZFlR2fueHTX4QLO66OklfPIaKrhXQ/zkqD0bdeRjdOxx/kxi740R599xwNtU5WLmqktjleMVGVNAaRJLQKzWUevpbhSFRd8m4P1FJTZfNOgxGbiLbR201zCo+Nk=
  - secure: A9+TvgnPK9ZzstfWK4d805QTOx86oPG2FGZq360kXOaMbYU9w5HhSOPiAMpfkbIrin5p3oBtOBcJwlXDXgPwrmEHUuH6tRgIsDNKSJGwdAVaAfGsoygeqGpeHhJt4xuzVHtzehbkBvLBhEIVrWBCNvtYq/EsoIi62CrUMyE5MeQ=
  - secure: TE5aWwOkvV2ItekEG1qUxrQBJSmOXnzsA6WxZe6q7wOUR0ub1jLN9Oe/QCZQDxhB0QojfZd44jIYZtXliURnB7unmHhkP+IMbc/tiZHwfxel+a9p3rSYU534hdBka3BzYuwCewbAOhIL80sk1tAuXk0JiHA5eHQz/pxeNnEfTOg=
  - secure: PQ5P9PdiD1YoMe828GRrSrUpTj6buUJWWRN7CznBHBiF7OsXYZFtXyXfvVLjM8ZExyFMIxU5CFCrFyWWTXpQ7acaEpxp4HEgaxrOCg0HVaWBK83O77QaTDNYjF9/bHua9GA6OCxvUYZ1Mnf+DOLLVEtR30xs2qZF78DXhUF/W0c=
  - secure: UX8GYd5N5RV75gIapzU9wahdNoVLW1sJn0bQTN0t08wJT9K8grWyt5X508WK6r6nJFEbNVf+SvEcH9/TOqj5cr16TiMM47GY04+Uy1/usQAfE/WzuS1s0aaW8UKKka4fc3EJW1xxXSdBFUsDxqc512y1AvQar9TY16OCEigVyes=
  - secure: DkoFGUmCXOQcbNl7j3mvDQmtbDcD9ihp3/vycND7rz6V1mb1pb3EpaENUR+mm+93rV9IBsSegk0XE4nsVc6zAxXlo+i7CzWlN19k0RLD2lPRtD0yQgc2GG/Z7rHn01RfzFfG7OOZoDQUBHqCcH2iWz4E/Jr00ELsW6EE3kt1vMQ=
  - secure: IqnB4KOlXvH4758+RJl5tQ2NWpDSGoU8yZLZRDYT39/epACHyuKBruXuc6RIakNug/GizM9FVuAuEdEz351HZXQow+8H1dZ33cmxfy7Ppe3d1qCFFqgjzh/Q1pnTRRajRQpDHgU/fDZVAGG8AYE6ox16/IZOI32Wp387UIph7xM=
  - secure: P0xhr2uVJYHpkGrN5PM9AcIU7abeuHL4p6PLP6e8uHGvMmtm0UUd0GtIu8W0lgs+wNzJosJ4p9q1fCjWydgHofYXh0DBN7NsE35IbD7lfcWZQUxhvsVt1kJeki0O4jguZUH8C4hgEXIDfvcIB6tlUm5y75DLsY3o95ZrUayQ1M0=
  - secure: Eaez6RAQ/BnMIk4WFz1oWwB1GBPZmtDFPHRkcQmfO+FB8PzskY3xgq7dhN2CewNzJjRb8Rl/lJjvn7H8o8u7eaeAL4VYDkxyKtZ2HHEN3Lu1nc1AL4c6Gr5PWvQivUgutWkR/ZP+/S6URjaOptp4kj3Dw4cBKzSIVt184dnU9kc=
  - secure: UqC5LuvJNSHFAwYB4enY2ED1vVvYiGvY8HLo9YUDnXm7uvL6bzajWXngQq+XaH47VogRBUCIIQTmHG2zbhEhDkmNn5IKjkUOVMXTFQtdNOlM6wdeZRLusfi/XC/Lm2NUXPgTRcYL6pWL8WLUcjyjYZKELDhEPgc7mbayv/UJEog=
  matrix:
  - KITCHEN_INSTANCE='ubuntu-1404'
  #- KITCHEN_INSTANCE='ubuntu-1310'
  #- KITCHEN_INSTANCE='ubuntu-1204'
  #- KITCHEN_INSTANCE='ubuntu-1004'
  #- KITCHEN_INSTANCE='debian-6'
  #- KITCHEN_INSTANCE='debian-7'
  #- KITCHEN_INSTANCE='centos-5'
  #- KITCHEN_INSTANCE='centos-6'
